#!/usr/bin/make -rRf
SHELL = /bin/sh -e

VENDOR := $(shell dpkg-vendor --derives-from Ubuntu && \
            echo ubuntu || echo debian)
include /usr/share/dpkg/pkg-info.mk

# since some files and/or lists differ from version to version,
# ensure we have the expected qemu version, or else scream loudly
checked-version := 9.0.2+ds

user-targets := \
 aarch64 \
 aarch64_be \
 alpha \
 arm \
 armeb \
 cris \
 hexagon \
 hppa \
 i386 \
 loongarch64 \
 m68k \
 microblaze \
 microblazeel \
 mips \
 mips64 \
 mips64el \
 mipsel \
 mipsn32 \
 mipsn32el \
 nios2 \
 or1k \
 ppc \
 ppc64 \
 ppc64le \
 riscv32 \
 riscv64 \
 s390x \
 sh4 \
 sh4eb \
 sparc \
 sparc32plus \
 sparc64 \
 x86_64 \
 xtensa \
 xtensaeb \
#

ifneq (${checked-version},${DEB_VERSION_UPSTREAM})
$(warning Debian packaging is set up for version ${checked-version} while actual version is ${DEB_VERSION_UPSTREAM})

actual-user-targets := $(sort $(shell \
  ls -1 configs/targets/*-linux-user.mak \
   | sed 's|.*/\(.*\)-linux-user\.mak$$|\1|'))
ifneq ($(sort ${user-targets}),${actual-user-targets})
$(warning user-targets list differs from actual, \
  added: $(filter-out ${user-targets},${actual-user-targets}), \
  removed: $(filter-out ${actual-user-targets},${user-targets}))
$(warning Check binfmt setup too!)
endif

$(error verify everything is set up correctly)
endif

# Host architectures we produce packages for.
# when changing this list, check d/control-in too, if any changes
# needs to be done for build deps and --enable options.
system-arch-linux-64 = \
	amd64 arm64 loong64 mips64 mips64el ppc64 ppc64el riscv64 s390x sparc64
system-arch-linux = $(sort ${system-arch-linux-64} \
	arm armel armhf i386 mips mipsel powerpc powerpcspe sparc)
system-arch = ${system-arch-linux}
user-arch = ${system-arch-linux}
utils-arch = $(sort ${system-arch} alpha hppa m68k sh4 x32)
# subset of system-arch
spice-arch = amd64 i386 arm64 armel armhf mips64el mipsel ppc64el

substvars = system-arch-linux-64 system-arch-linux system-arch spice-arch user-arch utils-arch

debian/control: debian/control-in debian/control.mk
	sed -e '1i\# autogenerated file from debian/control-in' \
	    -e 's/^:${VENDOR}://' -e '/^:[a-z]*:/D' \
		$(foreach v,${substvars},-e 's/:$v:/${$v}/') \
		$< > $@.tmp
	mv -f $@.tmp $@
