#!/usr/bin/make -rRf
SHELL = /bin/sh -e

VENDOR ?= $(shell dpkg-vendor --derives-from Ubuntu && echo ubuntu || echo debian)

# Host architectures we produce packages for.
# when changing this list, check d/control-in too, if any changes
# needs to be done for build deps and --enable options.
system-arch-linux-64 = \
	amd64 arm64 loong64 mips64 mips64el ppc64 ppc64el riscv64 s390x sparc64
system-arch-linux = $(sort ${system-arch-linux-64} \
	arm armel armhf i386 mips mipsel powerpc powerpcspe sparc)
system-arch = ${system-arch-linux}
user-arch = ${system-arch-linux}
utils-arch = $(sort ${system-arch} alpha hppa m68k sh4 x32)
# subset of system-arch
spice-arch = amd64 i386 arm64 armel armhf mips64el mipsel ppc64el

substvars = system-arch-linux-64 system-arch-linux system-arch spice-arch user-arch utils-arch

debian/control: debian/control-in debian/control.mk
	sed -e '1i\# autogenerated file from debian/control-in' \
	    -e 's/^:${VENDOR}://' -e '/^:[a-z]*:/D' \
		$(foreach v,${substvars},-e 's/:$v:/${$v}/') \
		$< > $@.tmp
	mv -f $@.tmp $@
