debian/qemu-ifup etc/
debian/qemu-ifdown etc/

usr/share/man/man1/qemu-system.1
usr/share/qemu/trace-events-all
usr/bin/qemu-pr-helper
usr/share/man/man8/qemu-pr-helper.8
usr/share/man/man7/qemu-qmp-ref.7
usr/share/man/man7/qemu-block-drivers.7
usr/share/man/man7/qemu-cpu-models.7
usr/share/doc/qemu/system usr/share/doc/qemu-system-common
usr/bin/qemu-storage-daemon
usr/share/man/man1/qemu-storage-daemon.1
usr/share/man/man7/qemu-storage-daemon-qmp-ref.7

# linux-specific
usr/lib/qemu/qemu-bridge-helper
usr/lib/qemu/virtfs-proxy-helper
usr/share/man/man1/virtfs-proxy-helper.1

# common modules. gui modules has been moved into place in d/rules.
usr/lib/${DEB_HOST_MULTIARCH}/qemu/accel-tcg-*.so
usr/lib/${DEB_HOST_MULTIARCH}/qemu/audio-*.so
usr/lib/${DEB_HOST_MULTIARCH}/qemu/chardev-*.so
usr/lib/${DEB_HOST_MULTIARCH}/qemu/hw-*.so
usr/lib/${DEB_HOST_MULTIARCH}/qemu/ui-*.so
